source 'https://rubygems.org'

platforms :jruby do
  gem 'activerecord-jdbcmysql-adapter'
  gem 'jruby-openssl'
  gem 'json'
  gem 'therubyrhino'
end

platforms :ruby do
  gem 'mysql2'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'jquery-ui-rails'
  gem 'compass-rails'
  gem 'uglifier', '>= 1.0.3'
end

gem 'rails', '3.2.8'
gem 'jquery-rails'
gem 'kaminari'
gem 'devise'
gem 'omniauth-facebook'
gem 'fb_graph'
gem 'high_voltage'
gem 'paperclip', '2.7.4'